# Generated by Django 4.1.7 on 2023-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/default-photo.png', null=True, upload_to=''),
        ),
    ]
